backend:
  name: github
  repo: furquan-lp/tctp.xyz
  branch: master

local_backend: true

media_folder: content/images
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title, widget: 'string' }
      - { name: author, label: Author, widget: 'string' }
      - { name: date, label: Date, widget: date }
      - { name: thumbnail, label: Thumbnail, widget: 'image' }
      - { name: banner, label: Banner, widget: 'image' }
      - { name: tags, label: Tags, widget: 'list' }
      - { name: body, label: Body, widget: markdown }